apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-conf
  namespace: {{ .Release.Namespace  }}
data:
  bootstrap.sh: |-
    #!/bin/bash
    cd /doccano
    export PATH=$PATH:/home/doccano/.local/bin
    # install dependency
    python -m pip install doccano=={{ .Values.image.tag }}
    python -m pip install 'doccano[postgresql]=={{ .Values.image.tag }}'
    # Initialize database.
    doccano init
    # Create a super user.
    doccano createuser --username admin --password {{ .Values.ADMIN_PASSWORD }}

    # Start Task Thread
    doccano task &

    # Start web server.
    doccano webserver --port 8000
