apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name | trunc 63 }}-conf"
data:
  bootstrap.sh: |-
    #!/bin/bash
    # Montage CIFS

    echo "username=$SMB_USER" > /root/.smbcred
    echo "password=$SMB_PASSWORD" >> /root/.smbcred
    echo "domain=$SMB_DOMAIN" >> /root/.smbcred

    mkdir -p $SMB_DESTPATH

    mount -vvv -t cifs -o noperm,credentials=/root/.smbcred $SMB_SOURCEPATH $SMB_DESTPATH

    # Lancement WATCHDOG
    service watchdog start

    # copie de la conf mail
    cp /config/mail/msmtprc /etc/msmtprc

    # Lancement du serveur web apache
    /usr/sbin/apache2ctl -D FOREGROUND
---
{{- if .Values.mail.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name | trunc 63 }}-conf-mail"
data:
  msmtprc: |-
{{ .Values.mail.config | indent 4 }}
{{- end }}
---
{{- if .Values.cron.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name | trunc 63 }}-conf-mail-cron"
data:
  boot-cron.sh: |-
{{ .Values.cron.config | indent 4 }}
{{- end }}
